### ISSUE TITLE
Unable to send MMS messages with media, due to no port in MMSC and a timeout exception

### ISSUE THREAD

**Issue by afollestad** [klinker41/android-smsmms#68]
First, I noticed that the port is empty (the bottom line):

<img width="555" alt="screen shot 2017-02-14 at 4 08 45 pm" src="https://cloud.githubusercontent.com/assets/1820165/22951746/f27a52e0-f2cf-11e6-993b-543722b30366.png">

Which I think is the reason why connections timeout:

<img width="1026" alt="screen shot 2017-02-14 at 4 08 55 pm" src="https://cloud.githubusercontent.com/assets/1820165/22951753/f58fa32c-f2cf-11e6-8564-cd8071c0b8dd.png">

**Comment by afollestad** [comment]
This occurs specifically on Verizon, also.

**Comment by klinker41** [comment]
The port will default to 80 if not explicitly set. I don't remember what Verizon uses specifically.

The base of the problem is that there isn't a good way for non-system apps to read APN information, so it has to read them from resource files which aren't always good. If you can, I would highly suggest setting the `Settings#useSystemSending` option to true instead, it is much more consistent and doesn't need to worry about reading APNs.

**Comment by afollestad** [comment]
Ah, will do, thanks!

Feel free to close if you don't feel this is a necessary ticket to have open.

**Comment by klinker41** [comment]
Great, you can reopen if you don't find that option working for you.
