### ISSUE TITLE
MMS images always have the same name

### ISSUE THREAD

**Issue by klinker24** [klinker41/android-smsmms#83]
I got a report from a user today that whenever a friend tries to save an image from a different SMS app, it makes them rename the image. Whatever app that friend uses, must pull the image name off of the `MmsPart` instead of just generating a new name.

He was very distraught about it, for whatever reason.

It looks to me that [this line](https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/Transaction.java#L340) is the issue.

Every image sent from Pulse would get the name `image1`. In Pulse, we do not set the `imageNames` attribute on the messages.

@klinker41 would it work to just timestamp these names instead? 

```java
part.Name = (imageNames != null) ? imageNames[i] : ("image" + Calendar.getInstance().getTimeInMillis());
```

**Comment by klinker41** [comment]
I would use `System.currentTimeInMillis()` instead of creating a full calendar object, but yes that would probably do it. I think it would also help to add methods for adding media to a message and specifying a name for that media. Right now, media is added with a `null` name in https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/Message.java.

**Comment by klinker41** [comment]
I added some methods to set the media name to `Message` and changed the default to be based on timestamp: https://github.com/klinker41/android-smsmms/commit/f6f61b4a0bf3741f9a138d0b1b701f1b7e9dc00c

**Comment by klinker24** [comment]
Haha that is hilarious, I was literally just sitting down to make this change! Thanks 👍

**Comment by klinker41** [comment]
No problem. I'll let you bump the version number and pull it into pulse when you are ready.
