### ISSUE TITLE
useSystemSending to false not working

### ISSUE THREAD

**Issue by jamesp0** [klinker41/android-smsmms#84]
I have got similar issue as discused in [#69](https://github.com/klinker41/android-smsmms/issues/69)
Just downloaded your lib and sample and changed this setUseSystemSending to false and same exception appeared. I have been trying many differend settings of manifest and gradle but nothing worked. Debuging also showed me nothing specific. (tried on Honor and Huawei Android 6 and also Sony Android 5)
You suggested check permissions but it didnt helped me a lot (isnt that WRITE_SETTINGS permission already solved in your sample?).
Isn't there a problem that It is trying to send MMS data through cellular network instead of this apn connection? Or could that be a manufacturer problem (they block this kind of sending)?
I really want to have this process of sending in my hands and dont want to use system sending.

**Comment by dariusvelavicius** [comment]
My use case requires the app to send MMS when useSystemSending is set to false. I have overcome quite a few issues with Android 7.1.2 but now I'm stuck when OkHttpClient method getOutputStream(). I get 

```
E/MmsHttpClient: HTTP: IO failure
java.net.SocketException: No route to google.com; exhausted inet socket addresses: []
```

Does anyone have any idea how to solve this?

**Comment by klinker41** [comment]
There is no need to open a new issue if you are having the same problem as someone else.

I would highly recommend just using the system sending method on any devices where it is available, it is unreliable based on device and carrier otherwise. Using it is exactly the same as allowing the system to send an sms for you, you wouldn't rewrite that logic yourself so there isn't a reason to do it for MMS.
